#include "vr_os.h"
#include "vr_windows.h"
#include "Ntstrsafe.h"
#include "vr_message.h"

#include "vr_ksync_defs.h"

const WCHAR DeviceName[] = L"\\Device\\vrouterKsync";
const WCHAR DeviceSymLink[] = L"\\DosDevices\\vrouterKsync";

struct ksync_response {
    ULONG len;
    unsigned char data[NL_MSG_DEFAULT_SIZE];
};

#define KSYNC_QUEUE_SIZE (sizeof(struct ksync_response))

<<<<<<< 26429c0b2b21ea67aa4da553bf3cccb397440e32
static PDEVICE_OBJECT KsyncDeviceObject = NULL;
static BOOLEAN KsyncSymlinkCreated = FALSE;
=======
static int ToClean = 0;
extern PMDL mdl_mem;
>>>>>>> Removed section

#define SIOCTL_TYPE 40000
#define IOCTL_SIOCTL_METHOD_OUT_DIRECT \
    CTL_CODE( SIOCTL_TYPE, 0x901, METHOD_OUT_DIRECT , FILE_ANY_ACCESS )

struct mem_wrapper
{
    PVOID       pBuffer;
};

_Dispatch_type_(IRP_MJ_CREATE) DRIVER_DISPATCH KsyncDispatchCreate;
_Dispatch_type_(IRP_MJ_CLOSE) DRIVER_DISPATCH KsyncDispatchClose;
_Dispatch_type_(IRP_MJ_WRITE) DRIVER_DISPATCH KsyncDispatchWrite;
_Dispatch_type_(IRP_MJ_READ) DRIVER_DISPATCH KsyncDispatchRead;
_Dispatch_type_(IRP_MJ_READ) DRIVER_DISPATCH KsyncDeviceControl;

_Use_decl_annotations_ NTSTATUS
KsyncDispatchCreate(PDEVICE_OBJECT DriverObject, PIRP Irp)
{
    UNREFERENCED_PARAMETER(DriverObject);

    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return STATUS_SUCCESS;
}

_Use_decl_annotations_ NTSTATUS
KsyncDispatchClose(PDEVICE_OBJECT DriverObject, PIRP Irp)
{
    UNREFERENCED_PARAMETER(DriverObject);

    IoCompleteRequest(Irp, IO_NO_INCREMENT);

    return STATUS_SUCCESS;
}

_Use_decl_annotations_ NTSTATUS
KsyncDispatchWrite(PDEVICE_OBJECT DriverObject, PIRP Irp)
{
    int ret;
    struct vr_message request, *response;

    PIO_STACK_LOCATION IoStackIrp = NULL;
    PCHAR WriteDataBuffer = NULL;
    IoStackIrp = IoGetCurrentIrpStackLocation(Irp);

    if (Irp->MdlAddress == NULL)
    {
        Irp->IoStatus.Status = STATUS_INVALID_PARAMETER;
        Irp->IoStatus.Information = 0;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_INVALID_PARAMETER;
    }

    WriteDataBuffer = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, LowPagePriority | MdlMappingNoExecute);
    if (!WriteDataBuffer) {
        Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
        Irp->IoStatus.Information = 0;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    struct nlmsghdr* p_nlmsghdr = (struct nlmsghdr*)WriteDataBuffer;
    struct genlmsghdr* p_genlmsghdr = (struct genlmsghdr*)(WriteDataBuffer + sizeof(struct nlmsghdr));
    struct nlattr *p_nlattrr = (struct nlattr*)(WriteDataBuffer + sizeof(struct nlmsghdr) + sizeof(struct genlmsghdr));

    request.vr_message_buf = NLA_DATA(p_nlattrr);
    request.vr_message_len = NLA_LEN(p_nlattrr);

    DBG_UNREFERENCED_LOCAL_VARIABLE(p_nlmsghdr);
    DBG_UNREFERENCED_LOCAL_VARIABLE(p_genlmsghdr);

    ret = vr_message_request(&request);
    if (ret < 0) {
        if (vr_send_response(ret))
            return ret;
    }

    while ((response = vr_message_dequeue_response())) {
        struct ksync_response *resp = (struct ksync_response *)DriverObject->DeviceExtension;
        size_t message_size = sizeof(response->vr_message_len) + response->vr_message_len;

        ASSERTMSG("Response generated by dp-core is bigger than ksync buffer",
                  message_size <= KSYNC_QUEUE_SIZE);

        RtlCopyMemory(&resp->len, &response->vr_message_len, sizeof(resp->len));
        RtlCopyMemory(resp->data, response->vr_message_buf, resp->len);

        vr_message_free(response);
    }
    
    Irp->IoStatus.Status = STATUS_SUCCESS;
    Irp->IoStatus.Information = IoStackIrp->Parameters.Write.Length;

    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}

_Use_decl_annotations_ NTSTATUS
KsyncDispatchRead(PDEVICE_OBJECT DriverObject, PIRP Irp)
{
    UNREFERENCED_PARAMETER(DriverObject);

    PIO_STACK_LOCATION IoStackIrp = NULL;
    PCHAR ReadDataBuffer = NULL;

    IoStackIrp = IoGetCurrentIrpStackLocation(Irp);

    if (Irp->MdlAddress == NULL)
    {
        Irp->IoStatus.Status = STATUS_INVALID_PARAMETER;
        Irp->IoStatus.Information = 0;
        IoCompleteRequest(Irp, IO_NO_INCREMENT);
        return STATUS_INVALID_PARAMETER;
    }

    Irp->IoStatus.Information = 0;

    ReadDataBuffer = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, LowPagePriority | MdlMappingNoExecute);
    if (ReadDataBuffer != NULL && DriverObject->DeviceExtension != NULL) {
        struct ksync_response *resp = (struct ksync_response *)DriverObject->DeviceExtension;
        ULONG read_max_length = IoStackIrp->Parameters.Read.Length;

        // User-space utility asks for __at most__ `read_max_length` bytes
        if (resp->len > 0 && read_max_length >= resp->len) {
            RtlCopyMemory(ReadDataBuffer, resp->data, resp->len);
            Irp->IoStatus.Information = resp->len;
            resp->len = 0;
        }
    }
    
    Irp->IoStatus.Status = STATUS_SUCCESS;

    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}

VOID
KsyncDestroyDevice(PDRIVER_OBJECT DriverObject)
{
    UNICODE_STRING _DeviceSymLink;

    if (KsyncSymlinkCreated) {
        RtlUnicodeStringInit(&_DeviceSymLink, DeviceSymLink);
        IoDeleteSymbolicLink(&_DeviceSymLink);
        KsyncSymlinkCreated = FALSE;
    }
    if (KsyncDeviceObject != NULL) {
        IoDeleteDevice(KsyncDeviceObject);
        KsyncDeviceObject = NULL;
    }
}

_Use_decl_annotations_ NTSTATUS
KsyncDeviceControl(PDEVICE_OBJECT DriverObject, PIRP Irp)
{
    UNREFERENCED_PARAMETER(DriverObject);

    NTSTATUS ntStatus = STATUS_SUCCESS;
    PIO_STACK_LOCATION irpSp;
    void* UserVirtualAddress = NULL;
    struct mem_wrapper returnedValue;
    PVOID buffer = NULL;

    irpSp = IoGetCurrentIrpStackLocation(Irp);

    switch (irpSp->Parameters.DeviceIoControl.IoControlCode)
    {
        case IOCTL_SIOCTL_METHOD_OUT_DIRECT:

            UserVirtualAddress = MmMapLockedPagesSpecifyCache(
                mdl_mem,
                UserMode,
                MmNonCached,
                NULL,
                FALSE,
                NormalPagePriority);

            buffer = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, NormalPagePriority);

            if (!buffer) {
                Irp->IoStatus.Status = STATUS_INSUFFICIENT_RESOURCES;
                Irp->IoStatus.Information = 0;
                IoCompleteRequest(Irp, IO_NO_INCREMENT);
                return STATUS_INSUFFICIENT_RESOURCES;
            }

            returnedValue.pBuffer = UserVirtualAddress;
            RtlCopyMemory(buffer, &returnedValue, sizeof(struct mem_wrapper));
            Irp->IoStatus.Information = sizeof(struct mem_wrapper);
            ntStatus = STATUS_SUCCESS;

            break;

        default:

            ntStatus = STATUS_INVALID_DEVICE_REQUEST;
            break;
    }

    Irp->IoStatus.Status = ntStatus;

    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}


NTSTATUS
KsyncCreateDevice(PDRIVER_OBJECT DriverObject)
{
    UNICODE_STRING _DeviceName;
    UNICODE_STRING _DeviceSymLink;
    PDEVICE_OBJECT DeviceObject = NULL;
    NTSTATUS Status;

    Status = RtlUnicodeStringInit(&_DeviceName, DeviceName);
    if (!NT_SUCCESS(Status)) {
        DbgPrint("DeviceName RtlUnicodeStringInit Error: %d\n", Status);
        return Status;
    }

    Status = RtlUnicodeStringInit(&_DeviceSymLink, DeviceSymLink);
    if (!NT_SUCCESS(Status)) {
        DbgPrint("DeviceSymLink RtlUnicodeStringInit Error: %d\n", Status);
        return Status;
    }

    Status = IoCreateDevice(DriverObject, KSYNC_QUEUE_SIZE, &_DeviceName,
                            FILE_DEVICE_NAMED_PIPE, FILE_DEVICE_SECURE_OPEN,
                            FALSE, &DeviceObject);
    if (NT_SUCCESS(Status))
    {
        KsyncDeviceObject = DeviceObject;

#pragma prefast(push)
#pragma prefast(disable:28175, "we're just setting it, it's allowed")

        DriverObject->MajorFunction[IRP_MJ_CREATE] = KsyncDispatchCreate;
        DriverObject->MajorFunction[IRP_MJ_CLOSE] = KsyncDispatchClose;
        DriverObject->MajorFunction[IRP_MJ_WRITE] = KsyncDispatchWrite;
        DriverObject->MajorFunction[IRP_MJ_READ] = KsyncDispatchRead;
        DriverObject->MajorFunction[IRP_MJ_DEVICE_CONTROL] = KsyncDeviceControl;
#pragma prefast(pop)

        DeviceObject->Flags |= DO_DIRECT_IO;
        DeviceObject->Flags &= (~DO_DEVICE_INITIALIZING);

        Status = IoCreateSymbolicLink(&_DeviceSymLink, &_DeviceName);
        if (NT_SUCCESS(Status)) {
            KsyncSymlinkCreated = TRUE;
        } else {
            IoDeleteDevice(DeviceObject);
            KsyncDeviceObject = NULL;
        }
    } else {
        DbgPrint("IoCreateDevice failed. Error code: %d\n", Status);
    }

    return Status;
}
