
/*
 * Autogenerated file. DO NOT EDIT.
 */

const char *ContrailBuildInfo = "{\"build-info\": [{\"build-time\": \"2017-03-02 22:30:34.373000\", \"build-hostname\": \"sagarc-T460\", \"build-user\": \"unknown\", \"build-version\": \"3.1.1.0\"}]}";
